### PR TITLE
Sales

### PR DESCRIPTION
**Pull request by krissycaron**
Stuck on accessing the products array? doesn't seem to be able to have access.

### CODE REVIEW

**Comment by krissycaron** [comment]
@Thomaswaters05 can you please review? i have the cards printing new with everything season discount choosen.

**Comment by krissycaron** [comment]
YAY!!! its done!!! @thomaswater05!!!

**Comment by Thomaswaters05** [comment]
👍  I knew you would get it! You will need to tell me what solved the problem exactly. I am curious!! Good job dood!!!

**Comment by Thomaswaters05** [comment]
Also- Quick shout out for the pushes you did. Making small pushes with each step makes it easier to finish the final product. This is one that I see a ton on. I dig it!! The more you push/commit is great! I myself am STILL working on that LOL

**Pull request merged**
